fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy
        types:
          - python
        language: system
  - repo: local
    hooks:
      - id: system
        name: ruff format
        entry: poetry run ruff format
        types:
          - python
        language: system
  - repo: local
    hooks:
      - id: system
        name: ruff lint
        entry: poetry run ruff check --fix
        types:
          - python
        language: system
exclude: 'tests\.*'