apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: false
  - name: Jaeger
    type: jaeger
    orgOd: 1
    url: http://jaeger:16686
    access: proxy
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

